language: objective-c
osx_image: xcode10.2
before_install:
  - gem install cocoapods -v '1.6.1'
install:
  - ./install_swiftlint.sh
script:
  - gem install travis --no-document
  - travis lint .travis.yml --no-interactive
  - swiftlint
  - swift package generate-xcodeproj
  - xcodebuild clean build -project SCNPath.xcodeproj -scheme SCNPath-Package -destination "platform=iOS Simulator,name=iPhone Xs" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO ONLY_ACTIVE_ARCH=NO
  - pod lib lint
